---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
       update_cache: yes

  - name: install apache2 package
    apt:
       name: apache2
       state: latest

  - name: add php support for apache
    apt:
       name: libapache2-mod-php
       state: latest

  - name: copy default html file for site
    tags: apache,apache2
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: install unzip
    package:
      name: unzip

  - name: Install unzip package
    apt:
       name: unzip
       state: present

  - name: Download Terraform binary
    get_url:
      url: https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
      dest: /tmp/terraform.zip

  - name: Unzip Terraform binary
    unarchive:
      src: /tmp/terraform.zip
      dest: /usr/local/bin/
      remote_src: yes
      mode: "0755"
      owner: root
      group: root

- hosts: all
  become: true
  tasks:

  - name: add ssh key for elorm
    tags: always
    authorized_key:
         user: elorm
         key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICw/Y3UuDfVvqrGpnIA85Cx86ujeBYLHbsMlxN4TNbfd ansible"
