---

- hosts: all
  become: true
  tasks:

  - name: update apt package manager cache
    apt:
       update_cache: yes

  - name: install nginx package
    ansible.builtin.apt:
       name: nginx
       state: latest
